-- Seed file for Schema-Aware LLM SQL Extension
-- This registers the tool, the planner, and sample knowledge without colliding with existing DBKG

-- ==========================================
-- 1. Create a specific test intent for dynamic SQL
-- ==========================================
DELETE FROM ce_intent WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_intent (intent_code, description, display_name, llm_hint, priority, enabled, created_at)
VALUES ('dynamic_sql', 'Dynamic SQL Execution Flow', 'Dynamic DB Query', 'Use this intent to run dynamic SQL queries based on db knowledge.', 100, true, CURRENT_TIMESTAMP);

-- ==========================================
-- 1b. Assign a deterministic Classifier Rule so you can easily invoke it
--     Type: "/sql Find all rejected requests" to force this intent.
-- ==========================================
DELETE FROM ce_intent_classifier WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_intent_classifier(
    intent_code, state_code, rule_type, pattern, priority, enabled, description
) VALUES
      ('dynamic_sql', 'UNKNOWN', 'STARTS_WITH', '/sql', 10, true, 'Force routing to the dynamic sql planner'),
      ('dynamic_sql', 'UNKNOWN', 'CONTAINS', 'dynamic sql', 20, true, 'Route if user explicitly asks for dynamic sql');

-- ==========================================
-- 2. Register the custom SQL Execution Tool globally (ANY intent/state)
--    so it doesn't collide with unique tool_code constraints, but remains available.
-- ==========================================
DELETE FROM ce_mcp_tool WHERE tool_code = 'postgres.query';
INSERT INTO ce_mcp_tool(
    tool_code, tool_group, intent_code, state_code, description, enabled, created_at
) VALUES (
             'postgres.query', 'DB', 'ANY', 'ANY', 'Execute raw read-only Postgres SQL generated by the LLM.', true, CURRENT_TIMESTAMP
         );

-- ==========================================
-- 3. Configure a specific MCP Planner ONLY for the 'dynamic_sql' intent
-- ==========================================
DELETE FROM ce_mcp_planner WHERE intent_code = 'dynamic_sql';
INSERT INTO ce_mcp_planner(
    intent_code, state_code, system_prompt, user_prompt, enabled, created_at
) VALUES (
             'dynamic_sql', 'ANY',
             'You are a DB expert. Your task is to plan table investigations.
         You have two main tools available:
         1. `db.knowledge.graph` - Pass keywords here to learn about tables, their columns, and see sample SQL queries before formulating your own.
         2. `postgres.query` - Pass the raw SELECT SQL query here once you know exactly what tables and columns to query.

         You must follow these steps:
         1. If you do not know the exact schema or queries for the users request, invoke `db.knowledge.graph` to get hints.
         2. Based on the domain semantic knowledge, generate a safe and read-only SELECT query.
         3. Submit the SQL query to `postgres.query`.
         4. Based on the returned rows, answer the user. Do NOT format final responses as JSON. Provide a clear, natural language summary.',
             'User request: {{user_input}}

         Available tools:
         {{available_tools}}

         Existing context:
         {{mcp_observations}}

         Formulate your next step.',
             true, CURRENT_TIMESTAMP
         );

-- ==========================================
-- 4. Seed Schema Semantic Knowledge
--    Tell the LLM what the tables and columns mean
-- ==========================================
DELETE FROM ce_mcp_schema_knowledge;
INSERT INTO ce_mcp_schema_knowledge(
    schema_name, table_name, column_name, data_type, description, llm_hint, is_active, created_date, updated_date
) VALUES
      ('public', 'zp_request', NULL, 'TABLE', 'Primary table storing customer provisioning requests', 'Join this table when the user asks about a request or order by connections. Contains zp_request_id.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('public', 'zp_request', 'zp_request_id', 'INTEGER', 'Unique request identifier', 'Used as the primary key and join key across all tables.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('public', 'zp_ui_data', NULL, 'TABLE', 'Current state data for UI interactions', 'Holds the latest status or action code for the request.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('public', 'zp_ui_data_history', NULL, 'TABLE', 'Historical log of UI state changes and assignments', 'Use this table for audits or finding when a request moved from one state to another (e.g. ASSIGNED to REJECTED). Compare different rows with the same zp_request_id but different action_ids over time.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ==========================================
-- 5. Seed Query Semantic Knowledge
--    Provide sample queries the LLM can adapt
-- ==========================================
DELETE FROM ce_mcp_query_knowledge;
INSERT INTO ce_mcp_query_knowledge(
    query_name, description, sample_sql, llm_hint, is_active, created_date, updated_date
) VALUES
    ('Find Rejected Requests recently', 'Finds requests that transitioned from ASR assigned to rejected in the last 24 hours',
     'SELECT h2.zp_request_id, h1.created_date AS assigned_at, h2.created_date AS rejected_at
     FROM zp_ui_data_history h1
     JOIN zp_ui_data_history h2 ON h1.zp_request_id = h2.zp_request_id AND h1.created_date < h2.created_date
     WHERE h1.zp_action_id = ''200'' AND h2.zp_action_id = ''400''
     AND h2.created_date >= NOW() - INTERVAL ''24 HOURS''
     ORDER BY h2.created_date DESC',
     'If asked about requests moving states (like ASR assigned to rejected), use this pattern against zp_ui_data_history. Replace the action_ids with appropriate values based on the status dictionary if known.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Make sure db.knowledge.graph is available globally
INSERT INTO ce_mcp_tool(
    tool_code, tool_group, intent_code, state_code, description, enabled, created_at
) SELECT 'db.knowledge.graph', 'DB', 'ANY', 'ANY', 'Semantic query/schema knowledge retrieval for similar issue diagnosis', true, CURRENT_TIMESTAMP
    WHERE NOT EXISTS (SELECT 1 FROM ce_mcp_tool WHERE tool_code = 'db.knowledge.graph');
